### Obtener portes en XML
GET http://localhost:3000/api/portes

### Obtener portes en JSON
GET http://localhost:3000/api/portes/json

### Obtener categorías
GET http://localhost:3000/api/categorias

### Añadir nuevo porte
POST http://localhost:3000/api/portes
Content-Type: application/json

{
  "especial": false,
  "contenedores": [
    {
      "tipo": "box",
      "mercancia": "fruta",
      "producto": "Naranjas"
    }
  ]
}

### Cargar módulo CSS
GET http://localhost:3000/gestionarCSSyToast.js

### Cargar datos stringificados
GET http://localhost:3000/portes.estringuificados.js